# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: localhost
title:  Colin Z. M.
email: zlma5220@gmail.com
author:  Colin Zili Ma
description: > # " Colin Zili Ma's Personal Page"

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty
# Build sitemap
gems:
  - jekyll-sitemap

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  # - icon: medium
  #   title: blog
  #   url: https://medium.com/thoughts-and-notes
  - icon: envelope-o
    title: email
    url: mailto:zlma5220@gmail.com
  - icon: github
    title: github
    url: https://github.com/mzlcuhk
  - icon: linkedin
    title: linkedin
    url: https://www.linkedin.com/in/zilima/
  #- icon: file-pdf-o
  #  title: resume
  #  url: http://www.wesleyq.me/rsc/resume.pdf
